name: /Users/karthik/Desktop/Power_forecast/.conda
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.12.0=pyhcf101f3_0
  - aom=3.6.0=hcec6c5f_0
  - appnope=0.1.4=py311hecd8cb5_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311hf197a57_2
  - asttokens=3.0.0=py311hecd8cb5_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=24.3.0=py311hecd8cb5_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - blas=1.0=openblas
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - bottleneck=1.4.2=py311h9b7fc35_0
  - brotli-python=1.0.9=py311h6d0c2b6_9
  - brotlicffi=1.0.9.2=py311h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.16.0=h08824b9_6
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py311h9205ec4_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py311hecd8cb5_0
  - contourpy=1.3.1=py311h1962661_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h6c40b1e_0
  - debugpy=1.8.11=py311h6d0c2b6_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - et_xmlfile=1.1.0=py311hecd8cb5_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6d0c2b6_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.55.3=py311h46256e1_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - gettext=0.21.0=h4e8c18a_2
  - graphite2=1.3.14=he9d5cce_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=h060d35a_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=hcec6c5f_0
  - idna=3.7=py311hecd8cb5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=py311hecd8cb5_1
  - ipython=8.15.0=py311hecd8cb5_0
  - jedi=0.19.2=py311hecd8cb5_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.1=py311hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonschema=4.25.0=py311hecd8cb5_0
  - jsonschema-specifications=2023.7.1=py311hecd8cb5_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.8.1=py311hecd8cb5_0
  - jupyter_events=0.12.0=py311hecd8cb5_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - kiwisolver=1.4.8=py311h6d0c2b6_0
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libavif=1.1.1=h46256e1_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libopenblas=0.3.29=h3f8574a_0
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=3.0.3=py311he13f9b5_0
  - matplotlib=3.10.0=py311hecd8cb5_0
  - matplotlib-base=3.10.0=py311h919b35b_0
  - matplotlib-inline=0.1.6=py311hecd8cb5_0
  - mistune=3.1.4=pyhcf101f3_0
  - narwhals=1.31.0=py311hecd8cb5_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=py311hecd8cb5_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=py311hecd8cb5_0
  - notebook=7.5.0=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numexpr=2.11.0=py311h20bc273_0
  - numpy=1.26.4=py311h91b6869_0
  - numpy-base=1.26.4=py311hb3ec012_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openpyxl=3.1.5=py311h46256e1_1
  - openssl=3.6.0=h230baf5_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=py311hecd8cb5_0
  - pandas=2.3.1=py311hebe84f7_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=py311hecd8cb5_0
  - patsy=1.0.1=py311hecd8cb5_0
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=py311hecd8cb5_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.3.0=py311h25d8182_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=hb254d66_0
  - platformdirs=4.3.7=py311hecd8cb5_0
  - plotly=6.0.1=py311he13d532_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.43=py311hecd8cb5_0
  - psutil=5.9.0=py311h46256e1_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py311hecd8cb5_0
  - pyparsing=3.2.0=py311hecd8cb5_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0post0=py311hecd8cb5_2
  - python-fastjsonschema=2.20.0=py311hecd8cb5_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=py311hecd8cb5_0
  - pyyaml=6.0.3=py311he13f9b5_0
  - pyzmq=24.0.1=py311habfacb3_1
  - readline=8.3=h49f2429_0
  - referencing=0.30.2=py311hecd8cb5_0
  - requests=2.32.4=py311hecd8cb5_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.22.3=py311h83de92b_0
  - scikit-learn=1.7.1=py311h20cdf89_0
  - scipy=1.16.0=py311hcd1e4c7_0
  - seaborn=0.13.2=py311hecd8cb5_3
  - send2trash=1.8.2=py311hecd8cb5_1
  - setuptools=78.1.1=py311hecd8cb5_0
  - six=1.17.0=py311hecd8cb5_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.5=py311hbc138da_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=py311h85bffb1_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=h3a5a201_0
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.1=py311h46256e1_0
  - traitlets=5.14.3=py311hecd8cb5_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py311h46256e1_1
  - urllib3=2.5.0=py311hecd8cb5_0
  - wcwidth=0.2.13=py311hecd8cb5_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=hcec6c5f_0
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - eia-python==1.22
      - xgboost==3.1.2
prefix: /Users/karthik/Desktop/Power_forecast/.conda
